#pragma once
//====================================================================================
//Graphics_pch.h : precompiled header
//
//This code is part of Anubis Engine.
//
//Anubis Engine is a free game engine created as a fan project to be
//awesome platform for developing games!
//
//All sources can be found here:
//	https://github.com/Dgek/Anubis-Engine
//
//Demos based on Anubis Engine can be found here:
//	https://github.com/Dgek/Demos
//
//Copyright (c) 2013, Muralev Evgeny
//All rights reserved.
//
//Redistribution and use in source and binary forms, with
//or without modification, are permitted provided that the
//following conditions are met:
//
//Redistributions of source code must retain the above copyright notice,
//this list of conditions and the following disclaimer.
//
//Redistributions in binary form must reproduce the above copyright notice,
//this list of conditions and the following disclaimer in the documentation
//and/or other materials provided with the distribution.
//
//Neither the name of the Minotower Games nor the names of its contributors 
//may be used to endorse or promote products derived from this software 
//without specific prior written permission.
//
//THIS SOFTWARE IS PROVIDED BY MURALEV EVGENY "AS IS"
//AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
//THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
//ARE DISCLAIMED. IN NO EVENT SHALL MURALEV EVGENY BE LIABLE
//FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
//(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
//ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//====================================================================================
#include <d3d11.h>
#include <d3dx11.h>
#include <D3DX10.h>
#include <d3dcompiler.h>
#include <memory>
#include <assert.h>

#include <Anubis.h>

using namespace std;

#define ADX11_API
//#define DXUT11_FW

///////////////////////////////////////////
//Input Assembler state
///////////////////////////////////////////
#define IA_PER_VERTEX_DATA	D3D11_INPUT_PER_VERTEX_DATA

///////////////////////////////////////////
//Enumerations
///////////////////////////////////////////
enum ShaderType
	{
		ST_Vertex,
		ST_Hull,
		ST_Domain,
		ST_Geometry,
		ST_Pixel,
		ST_Compute,
		VERTEX_SHADER = ST_Vertex,
		HULL_SHADER = ST_Hull,
		DOMAIN_SHADER = ST_Domain,
		GEOMETRY_SHADER = ST_Geometry,
		PIXEL_SHADER = ST_Pixel,
		COMPUTE_SHADER = ST_Compute,
		vertex_shader = ST_Vertex,
		hull_shader = ST_Hull,
		domain_shader = ST_Domain,
		geometry_shader = ST_Geometry,
		pixel_shader = ST_Pixel,
		compute_shader = ST_Compute,
	}; 

///////////////////////////////////////////
//Texture formats
#define TEX_R32G32B32_TYPELESS				DXGI_FORMAT_R32G32B32_TYPELESS         
#define	TEX_R32G32B32_FLOAT					DXGI_FORMAT_R32G32B32_FLOAT           
#define	TEX_R32G32B32_UINT					DXGI_FORMAT_R32G32B32_UINT          
#define	TEX_R32G32B32_SINT					DXGI_FORMAT_R32G32B32_SINT            
#define	TEX_R16G16B16A16_TYPELESS			DXGI_FORMAT_R16G16B16A16_TYPELESS      
#define	TEX_R16G16B16A16_FLOAT 				DXGI_FORMAT_R16G16B16A16_FLOAT        
#define	TEX_R16G16B16A16_UNORM  			DXGI_FORMAT_R16G16B16A16_UNORM    
///////////////////////////////////////////

#define TEX_UNKNOWN							DXGI_FORMAT_UNKNOWN
#define TEX_R32G32B32A32_TYPELESS			DXGI_FORMAT_R32G32B32A32_TYPELESS 
#define TEX_R32G32B32A32_FLOAT				DXGI_FORMAT_R32G32B32A32_FLOAT
#define TEX_R32G32B32A32_UINT				DXGI_FORMAT_R32G32B32A32_UINT         
#define TEX_R32G32B32A32_SINT				DXGI_FORMAT_R32G32B32A32_SINT    
#define	TEX_R16G16B16A16_UINT 				DXGI_FORMAT_R16G16B16A16_UINT        
#define	TEX_R16G16B16A16_SNORM				DXGI_FORMAT_R16G16B16A16_SNORM        
#define	TEX_R16G16B16A16_SINT				DXGI_FORMAT_R16G16B16A16_SINT         
#define	TEX_R32G32_TYPELESS					DXGI_FORMAT_R32G32_TYPELESS         
#define	TEX_R32G32_FLOAT					DXGI_FORMAT_R32G32_FLOAT              
#define	TEX_R32G32_UINT						DXGI_FORMAT_R32G32_UINT               
#define	TEX_R32G32_SINT						DXGI_FORMAT_R32G32_SINT               
#define	TEX_R32G8X24_TYPELESS				DXGI_FORMAT_R32G8X24_TYPELESS          
#define	TEX_D32_FLOAT_S8X24_UINT			DXGI_FORMAT_D32_FLOAT_S8X24_UINT      
#define	TEX_R32_FLOAT_X8X24_TYPELESS		DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS    
#define	TEX_X32_TYPELESS_G8X24_UINT			DXGI_FORMAT_X32_TYPELESS_G8X24_UINT     
#define	TEX_R10G10B10A2_TYPELESS			DXGI_FORMAT_R10G10B10A2_TYPELESS       
#define	TEX_R10G10B10A2_UNORM				DXGI_FORMAT_R10G10B10A2_UNORM          
#define	TEX_R10G10B10A2_UINT				DXGI_FORMAT_R10G10B10A2_UINT           
#define	TEX_R11G11B10_FLOAT					DXGI_FORMAT_R11G11B10_FLOAT             
#define	TEX_R8G8B8A8_TYPELESS				DXGI_FORMAT_R8G8B8A8_TYPELESS          
#define	TEX_R8G8B8A8_UNORM					DXGI_FORMAT_R8G8B8A8_UNORM             
#define	TEX_R8G8B8A8_UNORM_SRGB				DXGI_FORMAT_R8G8B8A8_UNORM_SRGB        
#define	TEX_R8G8B8A8_UINT					DXGI_FORMAT_R8G8B8A8_UINT              
#define	TEX_R8G8B8A8_SNORM					DXGI_FORMAT_R8G8B8A8_SNORM            
#define	TEX_R8G8B8A8_SINT					DXGI_FORMAT_R8G8B8A8_SINT            
#define	TEX_R16G16_TYPELESS					DXGI_FORMAT_R16G16_TYPELESS          
#define	TEX_R16G16_FLOAT					DXGI_FORMAT_R16G16_FLOAT            
#define	TEX_R16G16_UNORM					DXGI_FORMAT_R16G16_UNORM            
#define	TEX_R16G16_UINT						DXGI_FORMAT_R16G16_UINT               
#define	TEX_R16G16_SNORM					DXGI_FORMAT_R16G16_SNORM              
#define	TEX_R16G16_SINT						DXGI_FORMAT_R16G16_SINT                 
#define	TEX_R32_TYPELESS					DXGI_FORMAT_R32_TYPELESS               
#define	TEX_D32_FLOAT						DXGI_FORMAT_D32_FLOAT               
#define	TEX_R32_FLOAT						DXGI_FORMAT_R32_FLOAT             
#define	TEX_R32_UINT						DXGI_FORMAT_R32_UINT              
#define	TEX_R32_SINT						DXGI_FORMAT_R32_SINT             
#define	TEX_R24G8_TYPELESS					DXGI_FORMAT_R24G8_TYPELESS           
#define	TEX_D24_UNORM_S8_UINT				DXGI_FORMAT_D24_UNORM_S8_UINT       
#define	TEX_R24_UNORM_X8_TYPELESS			DXGI_FORMAT_R24_UNORM_X8_TYPELESS     
#define	TEX_X24_TYPELESS_G8_UINT			DXGI_FORMAT_X24_TYPELESS_G8_UINT       
#define	TEX_R8G8_TYPELESS					DXGI_FORMAT_R8G8_TYPELESS          
#define	TEX_R8G8_UNORM						DXGI_FORMAT_R8G8_UNORM            
#define	TEX_R8G8_UINT						DXGI_FORMAT_R8G8_UINT               
#define	TEX_R8G8_SNORM						DXGI_FORMAT_R8G8_SNORM          
#define	TEX_R8G8_SINT						DXGI_FORMAT_R8G8_SINT               
#define	TEX_R16_TYPELESS					DXGI_FORMAT_R16_TYPELESS
#define	TEX_R16_FLOAT						DXGI_FORMAT_R16_FLOAT               
#define	TEX_D16_UNORM						DXGI_FORMAT_D16_UNORM              
#define	TEX_R16_UNORM						DXGI_FORMAT_R16_UNORM               
#define	TEX_R16_UINT						DXGI_FORMAT_R16_UINT             
#define	TEX_R16_SNORM						DXGI_FORMAT_R16_SNORM          
#define	TEX_R16_SINT						DXGI_FORMAT_R16_SINT              
#define	TEX_R8_TYPELESS						DXGI_FORMAT_R8_TYPELESS            
#define	TEX_R8_UNORM						DXGI_FORMAT_R8_UNORM                
#define	TEX_R8_UINT							DXGI_FORMAT_R8_UINT                
#define	TEX_R8_SNORM						DXGI_FORMAT_R8_SNORM            
#define	TEX_R8_SINT							DXGI_FORMAT_R8_SINT            
#define	TEX_A8_UNORM						DXGI_FORMAT_A8_UNORM            
#define	TEX_R1_UNORM						DXGI_FORMAT_R1_UNORM              
#define	TEX_R9G9B9E5_SHAREDEXP				DXGI_FORMAT_R9G9B9E5_SHAREDEXP      
#define	TEX_R8G8_B8G8_UNORM					DXGI_FORMAT_R8G8_B8G8_UNORM         
#define	TEX_G8R8_G8B8_UNORM					DXGI_FORMAT_G8R8_G8B8_UNORM          
#define	TEX_BC1_TYPELESS					DXGI_FORMAT_BC1_TYPELESS              
#define	TEX_BC1_UNORM						DXGI_FORMAT_BC1_UNORM                   
#define	TEX_BC1_UNORM_SRGB					DXGI_FORMAT_BC1_UNORM_SRGB            
#define	TEX_BC2_TYPELESS					DXGI_FORMAT_BC2_TYPELESS                
#define	TEX_BC2_UNORM						DXGI_FORMAT_BC2_UNORM                  
#define	TEX_BC2_UNORM_SRGB					DXGI_FORMAT_BC2_UNORM_SRGB             
#define	TEX_BC3_TYPELESS					DXGI_FORMAT_BC3_TYPELESS                
#define	TEX_BC3_UNORM						DXGI_FORMAT_BC3_UNORM                 
#define	TEX_BC3_UNORM_SRGB					DXGI_FORMAT_BC3_UNORM_SRGB            
#define	TEX_BC4_TYPELESS					DXGI_FORMAT_BC4_TYPELESS              
#define	TEX_BC4_UNORM						DXGI_FORMAT_BC4_UNORM                 
#define	TEX_BC4_SNORM						DXGI_FORMAT_BC4_SNORM                 
#define	TEX_BC5_TYPELESS					DXGI_FORMAT_BC5_TYPELESS              
#define	TEX_BC5_UNORM						DXGI_FORMAT_BC5_UNORM                 
#define	TEX_BC5_SNORM						DXGI_FORMAT_BC5_SNORM                 
#define	TEX_B5G6R5_UNORM					DXGI_FORMAT_B5G6R5_UNORM               
#define	TEX_B5G5R5A1_UNORM					DXGI_FORMAT_B5G5R5A1_UNORM          
#define	TEX_B8G8R8A8_UNORM					DXGI_FORMAT_B8G8R8A8_UNORM            
#define	TEX_B8G8R8X8_UNORM					DXGI_FORMAT_B8G8R8X8_UNORM              
#define	TEX_R10G10B10_XR_BIAS_A2_UNORM		DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM 
#define	TEX_B8G8R8A8_TYPELESS				DXGI_FORMAT_B8G8R8A8_TYPELESS         
#define	TEX_B8G8R8A8_UNORM_SRGB				DXGI_FORMAT_B8G8R8A8_UNORM_SRGB        
#define	TEX_B8G8R8X8_TYPELESS				DXGI_FORMAT_B8G8R8X8_TYPELESS          
#define	TEX_B8G8R8X8_UNORM_SRGB				DXGI_FORMAT_B8G8R8X8_UNORM_SRGB       
#define	TEX_BC6H_TYPELESS					DXGI_FORMAT_BC6H_TYPELESS             
#define	TEX_BC6H_UF16						DXGI_FORMAT_BC6H_UF16                   
#define	TEX_BC6H_SF16						DXGI_FORMAT_BC6H_SF16                 
#define	TEX_BC7_TYPELESS					DXGI_FORMAT_BC7_TYPELESS             
#define	TEX_BC7_UNORM						DXGI_FORMAT_BC7_UNORM                 
#define	TEX_BC7_UNORM_SRGB					DXGI_FORMAT_BC7_UNORM_SRGB             
#define	TEX_AYUV							DXGI_FORMAT_AYUV                       
#define	TEX_Y410							DXGI_FORMAT_Y410                      
#define	TEX_Y416							DXGI_FORMAT_Y416                      
#define	TEX_NV12							DXGI_FORMAT_NV12                      
#define	TEX_P010							DXGI_FORMAT_P010                      
#define	TEX_P016							DXGI_FORMAT_P016                      
#define	TEX_420_OPAQUE						DXGI_FORMAT_420_OPAQUE                
#define	TEX_YUY2							DXGI_FORMAT_YUY2                       
#define	TEX_Y210							DXGI_FORMAT_Y210                     
#define	TEX_Y216							DXGI_FORMAT_Y216                       
#define	TEX_NV11							DXGI_FORMAT_NV11                      
#define	TEX_AI44							DXGI_FORMAT_AI44                        
#define	TEX_IA44							DXGI_FORMAT_IA44                      
#define	TEX_P8								DXGI_FORMAT_P8                          
#define	TEX_A8P8							DXGI_FORMAT_A8P8                      
#define	TEX_B4G4R4A4_UNORM					DXGI_FORMAT_B4G4R4A4_UNORM             
#define	TEX_FORCE_UINT						DXGI_FORMAT_FORCE_UINT            

///////////////////////////////////////////////////
//Primitive Topology
///////////////////////////////////////////////////
#define TOPOLOGY_UNDEFINED						D3D_PRIMITIVE_TOPOLOGY_UNDEFINED
#define TOPOLOGY_POINTLIST						D3D_PRIMITIVE_TOPOLOGY_POINTLIST
#define TOPOLOGY_LINELIST						D3D_PRIMITIVE_TOPOLOGY_LINELIST
#define TOPOLOGY_LINESTRIP						D3D_PRIMITIVE_TOPOLOGY_LINESTRIP
#define TOPOLOGY_TRIANGLELIST					D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST
#define TOPOLOGY_TRIANGLESTRIP					D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP
#define TOPOLOGY_LINELIST_ADJ					D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ
#define TOPOLOGY_LINESTRIP_ADJ					D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ
#define TOPOLOGY_TRIANGLELIST_ADJ				D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ
#define TOPOLOGY_TRIANGLESTRIP_ADJ				D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ
#define TOPOLOGY_UNDEFINED						D3D_PRIMITIVE_TOPOLOGY_UNDEFINED
#define TOPOLOGY_POINTLIST						D3D_PRIMITIVE_TOPOLOGY_POINTLIST
#define TOPOLOGY_LINELIST						D3D_PRIMITIVE_TOPOLOGY_LINELIST
#define TOPOLOGY_LINESTRIP						D3D_PRIMITIVE_TOPOLOGY_LINESTRIP
#define TOPOLOGY_TRIANGLELIST					D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST
#define TOPOLOGY_TRIANGLESTRIP					D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP
#define TOPOLOGY_LINELIST_ADJ					D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ
#define TOPOLOGY_LINESTRIP_ADJ					D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ
#define TOPOLOGY_TRIANGLELIST_ADJ				D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ
#define TOPOLOGY_TRIANGLESTRIP_ADJ				D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ
#define TOPOLOGY_1_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_2_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_3_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_4_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_5_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_6_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_7_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_8_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_9_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_10_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_11_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_12_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_13_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_14_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_15_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_16_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_17_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_18_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_19_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_20_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_21_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_22_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_23_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_24_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_25_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_26_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_27_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_28_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_29_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_30_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_31_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST
#define TOPOLOGY_32_PATCHLIST					D3D_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST

/////////////////////////////////////////////////////
//Filter
/////////////////////////////////////////////////////
#define FILTER_MIN_MAG_MIP_POINT									D3D11_FILTER_MIN_MAG_MIP_POINT                        
#define FILTER_MIN_MAG_POINT_MIP_LINEAR								D3D11_FILTER_MIN_MAG_POINT_MIP_LINEAR                   
#define FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT						D3D11_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT            
#define FILTER_MIN_POINT_MAG_MIP_LINEAR								D3D11_FILTER_MIN_POINT_MAG_MIP_LINEAR                  
#define	FILTER_MIN_LINEAR_MAG_MIP_POINT								D3D11_FILTER_MIN_LINEAR_MAG_MIP_POINT                   
#define FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR						D3D11_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR            
#define FILTER_MIN_MAG_LINEAR_MIP_POINT								D3D11_FILTER_MIN_MAG_LINEAR_MIP_POINT                  
#define FILTER_MIN_MAG_MIP_LINEAR									D3D11_FILTER_MIN_MAG_MIP_LINEAR                       
#define FILTER_ANISOTROPIC											D3D11_FILTER_ANISOTROPIC                                
#define FILTER_COMPARISON_MIN_MAG_MIP_POINT							D3D11_FILTER_COMPARISON_MIN_MAG_MIP_POINT                
#define	FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR					D3D11_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR         
#define FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT			D3D11_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT   
#define	FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR					D3D11_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR        
#define FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT					D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT         
#define FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR			D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR 
#define FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT					D3D11_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT        
#define FILTER_COMPARISON_MIN_MAG_MIP_LINEAR						D3D11_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR            
#define	FILTER_COMPARISON_ANISOTROPIC								D3D11_FILTER_COMPARISON_ANISOTROPIC                     
#define	FILTER_TEXT_1BIT											D3D11_FILTER_TEXT_1BIT

///////////////////////////////////////////////////////
//Texture address modes
///////////////////////////////////////////////////////
#define TEXTURE_ADDRESS_WRAP			D3D11_TEXTURE_ADDRESS_WRAP 
#define TEXTURE_ADDRESS_MIRROR			D3D11_TEXTURE_ADDRESS_MIRROR
#define TEXTURE_ADDRESS_CLAMP			D3D11_TEXTURE_ADDRESS_CLAMP
#define TEXTURE_ADDRESS_BORDER			D3D11_TEXTURE_ADDRESS_BORDER
#define TEXTURE_ADDRESS_MIRROR_ONCE		D3D11_TEXTURE_ADDRESS_MIRROR_ONCE

///////////////////////////////////////////////////////
//Comparison function
///////////////////////////////////////////////////////
#define COMPARISON_NEVER			D3D11_COMPARISON_NEVER
#define COMPARISON_LESS				D3D11_COMPARISON_LESS
#define COMPARISON_EQUAL			D3D11_COMPARISON_EQUAL  
#define COMPARISON_LESS_EQUAL		D3D11_COMPARISON_LESS_EQUAL 
#define COMPARISON_GREATER			D3D11_COMPARISON_GREATER 
#define COMPARISON_NOT_EQUAL		D3D11_COMPARISON_NOT_EQUAL 
#define COMPARISON_GREATER_EQUAL	D3D11_COMPARISON_GREATER_EQUAL
#define COMPARISON_ALWAYS			D3D11_COMPARISON_ALWAYS

#define MAX_FLOAT32					D3D11_FLOAT32_MAX

///////////////////////////////////////////////////////
//Blend
///////////////////////////////////////////////////////
#define BLEND_ZERO              D3D11_BLEND_ZERO
#define BLEND_ONE				D3D11_BLEND_ONE   
#define BLEND_SRC_COLOR			D3D11_BLEND_SRC_COLOR
#define BLEND_INV_SRC_COLOR     D3D11_BLEND_INV_SRC_COLOR
#define BLEND_SRC_ALPHA			D3D11_BLEND_SRC_ALPHA
#define BLEND_INV_SRC_ALPHA		D3D11_BLEND_INV_SRC_ALPHA
#define BLEND_DEST_ALPHA		D3D11_BLEND_DEST_ALPHA
#define BLEND_INV_DEST_ALPHA	D3D11_BLEND_INV_DEST_ALPHA
#define BLEND_DEST_COLOR		D3D11_BLEND_DEST_COLOR
#define BLEND_INV_DEST_COLOR	D3D11_BLEND_INV_DEST_COLOR
#define BLEND_SRC_ALPHA_SAT		D3D11_BLEND_SRC_ALPHA_SAT
#define BLEND_BLEND_FACTOR		D3D11_BLEND_BLEND_FACTOR
#define BLEND_INV_BLEND_FACTOR	D3D11_BLEND_INV_BLEND_FACTOR 
#define BLEND_SRC1_COLOR		D3D11_BLEND_SRC1_COLOR
#define BLEND_INV_SRC1_COLOR	D3D11_BLEND_INV_SRC1_COLOR
#define BLEND_SRC1_ALPHA		D3D11_BLEND_SRC1_ALPHA 
#define BLEND_INV_SRC1_ALPHA	D3D11_BLEND_INV_SRC1_ALPHA 

//////////////////////////////////////////////////////
//Blend operation
//////////////////////////////////////////////////////
#define BLEND_OP_ADD			D3D11_BLEND_OP_ADD    
#define BLEND_OP_SUBTRACT		D3D11_BLEND_OP_SUBTRACT
#define BLEND_OP_REV_SUBTRACT	D3D11_BLEND_OP_REV_SUBTRACT
#define BLEND_OP_MIN			D3D11_BLEND_OP_MIN 
#define BLEND_OP_MAX			D3D11_BLEND_OP_MAX 